### PR TITLE
Set dispatcher from Silex app

### PR DESCRIPTION
**Pull request by dirkluijk**
This proposal sets the default event dispatcher of Silex into the provided `ConsoleApplication`. This allows you to subscribe to the default `ConsoleEvents` that are dispatched inside the Symfony Console Application.

```
$app = require __DIR__.'/../app/app.php';

$app->on(ConsoleEvents::TERMINATE, function () use ($app) {
    // flush queue (for sending emails from command line)
    $app['swiftmailer.spooltransport']
        ->getSpool()
        ->flushQueue($app['swiftmailer.transport']);
});

$app->boot();
$app['console']->run();
```

### CODE REVIEW

**Comment by dirkluijk** [comment]
I see the master branch does not contain a specific Provider for Silex anymore, so maybe leave it out there?

**Comment by dominikzogg** [comment]
@dirkluijk well, we could check if the $app['swiftmailer.spooltransport'] and $app['swiftmailer.transport'] with isset

**Comment by dirkluijk** [comment]
Well, in that case it would only need to check for `dispatcher`. ;)

Above code is just a sample usage, which I have submitted a PR for in the official SwiftMailerProvider (see https://github.com/silexphp/Silex/pull/1131).

**Comment by dominikzogg** [comment]
@dirkluijk i would suggest to use the same changes as for v3, what do you mean?

**Comment by dirkluijk** [comment]
Done! :wink:

**Comment by dominikzogg** [comment]
@dirkluijk sorry, forgot to merge

**Comment by dominikzogg** [comment]
https://github.com/saxulum/saxulum-console/releases/tag/2.2.0

**Pull request merged**
